### ISSUE TITLE
Implement ability to read/output specific text files without any modification.

### ISSUE THREAD

**Issue by maxerium** [Vodes/osu-np-Bot#1]
As the issue title states, implement a feature so you can just give the bot a list of files from within the SC directory and assign seperate commands to each of them. That way you can allow custom formatting for the command output.

**Comment by Vodes** [comment]
Might redo the command system and add the ability make custom commands I guess. Give me a day or two.

**Comment by Vodes** [comment]
With v0.3 i now added a custom command system. Please try it and tell me if that's what you wanted.

**Comment by Vodes** [comment]
I'll consider this done if he doesnt answer.
