### ISSUE TITLE
np command always showing the same song

### ISSUE THREAD

**Issue by m84ef** [Vodes/osu-np-Bot#3]
pretty much the title

the dl doesn't work as well

Demo Video: https://youtu.be/GtbfT6YxYaI

**Comment by Vodes** [comment]
Can you check [my video](https://youtu.be/VEMzHbrBpnw?t=11) and compare your streamcompanion settings? It's pretty likely to be related to those.

**Comment by m84ef** [comment]
ok I could fix most of the problems, however the DL link is still missing 
![Bild_2021-08-08_235950](https://user-images.githubusercontent.com/88632011/128646950-46292843-da35-40e7-98a6-061a3c9950cd.png)

**Comment by Vodes** [comment]
Well check your Streamcompanion Directory and if there is a file called `np_playing_DL.txt`. If that is empty all the time, there's your issue.

**Comment by Vodes** [comment]
Considering this done.
